-- Drop existing tables to ensure a clean setup
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS site_content CASCADE;
DROP TABLE IF EXISTS faqs CASCADE;

-- Create a table for categories
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- RLS for categories table
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users to read categories" ON categories;
CREATE POLICY "Allow authenticated users to read categories" ON categories
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert categories" ON categories;
CREATE POLICY "Allow authenticated users to insert categories" ON categories
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update categories" ON categories;
CREATE POLICY "Allow authenticated users to update categories" ON categories
FOR UPDATE TO authenticated
USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete categories" ON categories;
CREATE POLICY "Allow authenticated users to delete categories" ON categories
FOR DELETE TO authenticated
USING (true);

-- Create a table for products
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  weight TEXT,
  image_url TEXT,
  category_id BIGINT,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Create a table for page-specific text content
CREATE TABLE site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL,
  element TEXT NOT NULL,
  content TEXT,
  UNIQUE (section, element)
);

-- RLS for site_content table
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to site_content" ON site_content;
CREATE POLICY "Allow public read access to site_content" ON site_content
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert site_content" ON site_content;
CREATE POLICY "Allow authenticated users to insert site_content" ON site_content
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update site_content" ON site_content;
CREATE POLICY "Allow authenticated users to update site_content" ON site_content
FOR UPDATE TO authenticated
USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete site_content" ON site_content;
CREATE POLICY "Allow authenticated users to delete site_content" ON site_content
FOR DELETE TO authenticated
USING (true);

-- Create a table for images
CREATE TABLE images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  section TEXT,
  url TEXT NOT NULL
);

-- RLS for images table
ALTER TABLE images ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to images" ON images;
CREATE POLICY "Allow public read access to images" ON images
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert images" ON images;
CREATE POLICY "Allow authenticated users to insert images" ON images
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update images" ON images;
CREATE POLICY "Allow authenticated users to update images" ON images
FOR UPDATE TO authenticated
USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete images" ON images;
CREATE POLICY "Allow authenticated users to delete images" ON images
FOR DELETE TO authenticated
USING (true);

-- Create a table for FAQs
CREATE TABLE faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL
);

-- Create a bucket for images
INSERT INTO storage.buckets (id, name, public)
VALUES ('website_images', 'website_images', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public;

-- Policies for storage.objects
DROP POLICY IF EXISTS "Allow public read access to images" ON storage.objects;
CREATE POLICY "Allow public read access to images" ON storage.objects
FOR SELECT
USING ( bucket_id = 'website_images' );

DROP POLICY IF EXISTS "Allow authenticated users to upload images" ON storage.objects;
CREATE POLICY "Allow authenticated users to upload images" ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'website_images' );

DROP POLICY IF EXISTS "Allow authenticated users to update their own images" ON storage.objects;
CREATE POLICY "Allow authenticated users to update their own images" ON storage.objects
FOR UPDATE
TO authenticated
USING ( bucket_id = 'website_images' AND auth.uid() = owner );

DROP POLICY IF EXISTS "Allow authenticated users to delete their own images" ON storage.objects;
CREATE POLICY "Allow authenticated users to delete their own images" ON storage.objects
FOR DELETE
TO authenticated
USING ( bucket_id = 'website_images' AND auth.uid() = owner );
